### ISSUE TITLE
AI Now - AI Lexicon / AI Ethics & inclusivity submission due ~ March

### ISSUE THREAD

**Issue by jesparent** [OREL-group/ethics-society#1]
This will be part of the ethics & society team. Various members & external collaborators from the lab are interested in this topic. See Slack & NYU’s AI Now medium post for more information. Open for collab!

https://medium.com/a-new-ai-lexicon/a-new-ai-lexicon-responses-and-challenges-to-the-critical-ai-discourse-f2275989fa62

Call for Contributors

Taking inspiration from Raymond Williams’ original Keywords project and more recently from media scholar Maya Ganesh’s work (A is for Another: A Dictionary of AI), we invite short essays or posts (1000–1500 words) that take up a dominant concept, metaphor or keyword along which critical AI thinking is currently undertaken. We invite reflections and responses to research themes and keywords foregrounded in critical AI conferences such as FaCCT but also writing that offers new terms or formulations absent from the discourse. We ask authors to respond, challenge, situate or re-frame the concept or metaphor they choose by drawing on archival, ethnographic, journalistic, critical quantitative research focusing on the global South or transnational contexts.

"In order to contribute to the New AI lexicon project please fill this form and attach a document containing two (or more) 300 word pitches for the essays you would like to contribute. We are accepting contributions on a rolling basis between January and March, and aim to publish before June 2021. Please mention if the research is already done or is in progress and what kind of resources you might need in order to complete the piece. Please provide your name, affiliation (if any) and links to your previous writings (if any)."

**Comment by jesparent** [comment]
This could be a great way to bridge some of the nYCWiC topics into smaller essays or adjacent knowledge creation @minhtranbear  et al

**Comment by krishnakatyal** [comment]
@jesparent  i would like to contribute on this :)

**Comment by Athene-ai** [comment]
@jesparent i would like to contribute on this :)

**Comment by jesparent** [comment]
@krishnakatyal hey! So you are here on github, too - great. are you in our lab slack? That's the center for much of our discussion. DM me your email on twitter if you want and I will ad you if you are not in there (I tried to @ you there but I can't seem to find your username if you are). @Athene-ai  thank you also for expressing interest. 

We have a slight immediate focus on the NYCWiC AI Ethics framework presentation, but there's a tremendous amount of overlap https://github.com/orgs/OREL-group/projects/6 . We're open to help on both of these projects for sure, so let us know!

**Comment by jesparent** [comment]
cc @Orthogonal-Research-Lab

**Comment by Athene-ai** [comment]
both of these projects :)

**Comment by jesparent** [comment]
https://medium.com/a-new-ai-lexicon/faqs-a-new-ai-lexicon-4ce705cd921f still accepting? to reach out @jesparent
