### ISSUE TITLE
Revise Abstract

### ISSUE THREAD

**Issue by jesparent** [OREL-group/ethics-society#11]

**Comment by jesparent** [comment]
Finished - thank you all for your submission ideas and information!

**Comment by Athene-ai** [comment]
my pleasure !

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
