### ISSUE TITLE
NYCWiC '21 Presentation

### ISSUE THREAD

**Issue by jesparent** [OREL-group/ethics-society#14]
We have 15-20 minutes to present. We'll do a brief overview, then a focus on specific topics within AI ethics, and then a conclusion. 

- [x] Set up Slides
- [x] Finalize Topics
- [x] Review Slides
- [x] Decide recording / presentation method (Waiting for NYCWiC to confirm if pre-recorded or not)

**Comment by Athene-ai** [comment]
Could you please send me the materials for the  NYCWiC's slides ?

Daniela


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jesparent** [comment]
good job team ! 

@minhtranbear  ty for showing up and presenting last second.
