### ISSUE TITLE
Topics: AI Bias & Neutrality

### ISSUE THREAD

**Issue by jesparent** [OREL-group/ethics-society#15]

**Comment by jesparent** [comment]
Zotero library of resources: https://www.zotero.org/groups/2574810/orel/collections/AQ63PAPK

**Comment by jesparent** [comment]
@Shruti-Raj-Vansh-Singh  

One way to start looking at this task

Think of a set of bullet points you'd like to cover about this topic that you could have 1-3 minutes of talking about within the broader presentation. What key points would you like to express to others who are just hearing or thinking about these topics for the first time, etc?

**Comment by Shruti-Raj-Vansh-Singh** [comment]
Understood! Will be working on it
